sudo: required
services:
- docker
branches:
  only:
  - master
  - travis_troubleshoot
script:
- "./run.sh npm install"
- "./run.sh gulp clean"
- "./run.sh gulp build --environment live"
- "./run.sh gulp deploy --environment live"
env:
  global:
    secure: ZEhL7lAizcG4sTx5tBgve2sI4QcpFo7Uj1aZe8Lny7WoxXzGyLV6Eppdj2WQU0OEzfo6Kx8ai+Cpehv4Tldi1zQh65ghg0yprUZKQc/HWlVUbKm2Sk68aKhtFvJLrG1d4lrm1phGCdFmaEXQpRFlKF2cMuCP2KwuQHJLqB/oJhA=
notifications:
  slack:
    secure: APHNQQXtuvSspQryi1oAHjh/GePQXEPyWkFILj63YdG/jmZXvaI+DaUVz/PvPRuTNPGfz8jubZvJvrsL3t0oJ9eWkue1VSfXTI1kSM7K+YNnJPp3KTYwSw0TxZNBU3o19JwrKdGz+3LLIQeY8fu+bdX58FUezwXo0drQwKlRsRE=
